### ISSUE TITLE
Can not install normalspeed on windows10 correctly

### ISSUE THREAD

**Issue by HannahHaensen** [hfutcgncas/normalSpeed#11]
i installed normalspeed and receive after the installation
```
git clone https://github.com/hfutcgncas/normalSpeed.git
cd normalSpeed/normalSpeed
python setup.py install --user
cd ..
```

```
Installed c:\users\admin\documents\github\ffb6d\venv\lib\site-packages\normalspeed-0.0.1-py3.9-win-amd64.egg
Processing dependencies for normalSpeed==0.0.1
Finished processing dependencies for normalSpeed==0.0.1

(venv) C:\Users\Admin\Documents\GitHub\FFB6D\normalSpeed\normalSpeed>python setup.py install 
```
but if i want to use it I receive
```
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2021.3.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'normalSpeed'
```

I use python 3.9, opencv 3.4... 
pybind11 (installed via pip)

**Comment by minareda417** [comment]
Hello,
did you solved this issue?
